/**
 * The contents of this file are subject to the AED Public Use License Agreement, Version 1.0 (the "License");
 * use in any manner is strictly prohibited except in compliance with the terms of the License.
 * The License is available at http://gatherdata.org/license.
 *
 * Copyright (c) AED.  All Rights Reserved
 */
package org.gatherdata.forms.dao.el.model;

import java.io.Serializable;
import java.net.URI;
import java.net.URISyntaxException;
import java.util.Calendar;

import org.apache.commons.lang.ObjectUtils;
import org.gatherdata.forms.core.model.FlatForm;
import org.gatherdata.forms.core.model.RenderedValue;

/**
 * ### Generated by EclipseLink Project EclipseLink Workbench Workbench Core
 * Library 1.0.2 - Fri Jan 23 18:21:32 EST 2009. ###
 */

public class ElRenderedValue implements RenderedValue {

	/**
     * 
     */
    private static final long serialVersionUID = 2249507556132843540L;
    
    private int id;
    private Calendar dateCreated;
    private ElFlatForm form;
    private URI namespace;
    private String path;
    private String tag;
    private boolean valueAsBoolean;
    private Calendar valueAsDate;
    private Calendar valueAsDateTime;
    private float valueAsFloat;
    private int valueAsInt;
    private String valueAsString;
    private boolean voided;
    
    public int getId() {
        return this.id;
    }

    public Calendar getDateCreated() {
        return this.dateCreated;
    }

    public void setDateCreated(Calendar dateCreated) {
        this.dateCreated = dateCreated;
    }
    
    public FlatForm getForm() {
        return this.form;
    }
    
    public void setForm(ElFlatForm form) {
        this.form = form;
    }

    public URI getNamespace() {
        return this.namespace;
    }
    
    public void setNamespace(URI namespace) {
        this.namespace = namespace;
    }

    public String getPath() {
        return this.path;
    }
    
    public void setPath(String path) {
        this.path = path;
    }

    public String getTag() {
        return this.tag;
    }

    public void setTag(String tag) {
        this.tag = tag;
    }
    
    public boolean getValueAsBoolean() {
        return this.valueAsBoolean;
    }

    public Calendar getValueAsDate() {
        return this.valueAsDate;
    }

    public Calendar getValueAsDateTime() {
        return this.valueAsDateTime;
    }
    
    public float getValueAsFloat() {
        return this.valueAsFloat;
    }

    public int getValueAsInt() {
        return this.valueAsInt;
    }

    public String getValueAsString() {
        return this.valueAsString;
    }

    public boolean isVoided() {
        return this.voided;
    }

	


}
